# Generated by Django 4.2.18 on 2026-06-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ref', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=20)),
                ('age_range', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('study_hours', models.CharField(max_length=30)),
                ('attendance', models.CharField(max_length=30)),
                ('courses_failed', models.CharField(max_length=20)),
                ('sleep_hours', models.CharField(max_length=20)),
                ('financial_stress', models.CharField(max_length=30)),
                ('mother_education', models.CharField(max_length=40)),
                ('father_education', models.CharField(max_length=40)),
                ('family_income', models.CharField(max_length=30)),
                ('part_time_work', models.CharField(max_length=30)),
                ('motivation', models.CharField(max_length=30)),
                ('stress_level', models.CharField(max_length=30)),
                ('self_rated_perf', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_class', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('recommendation', models.TextField()),
                ('feature_scores', models.JSONField(blank=True, default=list)),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
