# Generated by Django 4.2.18 on 2026-06-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age_range',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
