# Generated by Django 4.2.18 on 2026-06-13 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fix_model_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=120)),
                ('row_count', models.IntegerField(default=0)),
                ('rows', models.JSONField(default=list)),
                ('accuracy_after', models.FloatField(blank=True, null=True)),
                ('bias_report', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
